{
 "title": "ClickHouse",
 "time": { "from": "2014-11-29T07:43:11.779Z", "to": "2015-09-27T09:13:22.416Z" },
 "templating": {
  "list": [
   { "name": "table", "label": "table", "query": "stocks_analytics.stocks" },
   {
    "name": "company",
    "label": "company",
    "query": "select distinct company from $table"
   }
  ]
 },
 "panels": [
  {
   "title": "MAX High prices [TOP 10]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "stocks_analytics",
     "dateTimeColDataType": "toDateTime(date)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    company,\n    max(high) as high\nFROM $table\n\nWHERE $timeFilter and company in ('YHWSRMQ', 'JRPGDJ', 'WEDS', 'TDYBR', 'CND', 'XVK', 'BVCOQF', 'BFSDSU', 'DSUPZU', 'CLFMUWK')\n\nGROUP BY\n    t,\n    company\nORDER BY high desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(date)), 86400) * 86400) * 1000 as t,\n    company,\n    max(high) as high\nFROM stocks_analytics.stocks\n\nWHERE toDateTime(date) >= toDateTime(1444510800) AND toDateTime(date) <= toDateTime(1451163599) and company in ('YHWSRMQ', 'JRPGDJ', 'WEDS', 'TDYBR', 'CND', 'XVK', 'BVCOQF', 'BFSDSU', 'DSUPZU', 'CLFMUWK')\n\nGROUP BY\n    t,\n    company\nORDER BY high desc",
     "round": "0s",
     "table": "stocks"
    }
   ]
  },
  {
   "title": "High - Low Diff [TOP 10]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "stocks_analytics",
     "dateTimeColDataType": "toDateTime(date)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    company,\n    round(abs(high - low), 5) as diff_high_low\nFROM $table\n\nWHERE\n    $timeFilter\n    and company in ('YHWSRMQ','JRPGDJ','WEDS','TDYBR','CND','XVK','BVCOQF','BFSDSU','DSUPZU','CLFMUWK')\nGROUP BY\n    t,\n    company,\n    high,\n    low\nORDER BY diff_high_low desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(date)), 86400) * 86400) * 1000 as t,\n    company,\n    round(abs(high - low), 5) as diff_high_low\nFROM stocks_analytics.stocks\n\nWHERE\n    toDateTime(date) >= toDateTime(1444510800) AND toDateTime(date) <= toDateTime(1451163599)\n    and company in ('YHWSRMQ','JRPGDJ','WEDS','TDYBR','CND','XVK','BVCOQF','BFSDSU','DSUPZU','CLFMUWK')\nGROUP BY\n    t,\n    company,\n    high,\n    low\nORDER BY diff_high_low desc",
     "round": "0s",
     "table": "stocks"
    }
   ]
  },
  {
   "title": "Volume [$company]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "stocks_analytics",
     "dateTimeColDataType": "toDateTime(date)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    company,\n    SUM(volume) as volume\nFROM $table\n\nWHERE\n    $timeFilter\n    and company in ($company)\nGROUP BY\n    t,\n    company\nORDER BY volume desc",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(date)), 86400) * 86400) * 1000 as t,\n    company,\n    SUM(volume) as volume\nFROM stocks_analytics.stocks\n\nWHERE\n    toDateTime(date) >= toDateTime(1444510800) AND toDateTime(date) <= toDateTime(1451163599)\n    and company in ('A','AAP','ADSK','ADI','ACN')\nGROUP BY\n    t,\n    company\nORDER BY volume desc",
     "round": "0s",
     "table": "stocks"
    }
   ]
  },
  {
   "title": "Volume [$company]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "stocks_analytics",
     "dateTimeColDataType": "toDateTime(date)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    company,\n    SUM(volume) as volume\nFROM $table\n\nWHERE\n    $timeFilter\n    and company in ($company)\nGROUP BY\n    t,\n    company\nORDER BY volume desc",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(date)), 86400) * 86400) * 1000 as t,\n    company,\n    SUM(volume) as volume\nFROM stocks_analytics.stocks\n\nWHERE\n    toDateTime(date) >= toDateTime(1444510800) AND toDateTime(date) <= toDateTime(1451163599)\n    and company in ('A','AAP','ADSK','ADI','ACN')\nGROUP BY\n    t,\n    company\nORDER BY volume desc",
     "round": "0s",
     "table": "stocks"
    }
   ]
  },
  {
   "title": "Open quantile 0.75 [$company]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "stocks_analytics",
     "dateTimeColDataType": "toDateTime(date)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    company,\n    quantile(0.75)(high) as high\nFROM $table\n\nWHERE\n    $timeFilter\n    and company in ($company)\nGROUP BY\n    t,\n    company\nORDER BY high desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(date)), 86400) * 86400) * 1000 as t,\n    company,\n    quantile(0.75)(high) as high\nFROM stocks_analytics.stocks\n\nWHERE\n    toDateTime(date) >= toDateTime(1444510800) AND toDateTime(date) <= toDateTime(1451163599)\n    and company in ('AAP','AAPL')\nGROUP BY\n    t,\n    company\nORDER BY high desc",
     "round": "0s",
     "table": "stocks"
    }
   ]
  },
  {
   "title": "Low quantile 0.75 [$company]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "stocks_analytics",
     "dateTimeColDataType": "toDateTime(date)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    company,\n    quantile(0.75)(low) as low\nFROM $table\n\nWHERE\n    $timeFilter\n    and company in ($company)\nGROUP BY\n    t,\n    company\nORDER BY low desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toDateTime(date)), 86400) * 86400) * 1000 as t,\n    company,\n    quantile(0.75)(low) as low\nFROM stocks_analytics.stocks\n\nWHERE\n    toDateTime(date) >= toDateTime(1444510800) AND toDateTime(date) <= toDateTime(1451163599)\n    and company in ('AAP','AAPL')\nGROUP BY\n    t,\n    company\nORDER BY low desc",
     "round": "0s",
     "table": "stocks"
    }
   ]
  }
 ]
}