spring:
  application:
    name: clickhouse-stocks-loader

server:
  port: 8060
  servlet:
    context-path: /${spring.application.name}

management:
  endpoints.web.exposure.include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
      percentiles:
        http.client.requests: 0.50,0.75,0.95,0.99
    tags:
      application: ${spring.application.name}

loader:
  enabled: true
  batchSize: 10000

clickhouse:
  username: admin
  password: password
  jdbcUrl: jdbc:clickhouse://localhost:8123
  table: stocks_analytics.stocks

generator:
  enabled: true
  dateStart: '2012-08-13'
  dateEnd: '2017-08-11'
  companiesCount: 100

logging:
  level:
    tech.volkov: debug
